# Generated by Django 3.0 on 2020-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wiseword'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='Lijusa Member', max_length=255),
        ),
    ]
